"""K2 (routing) and K3 (the deterministic gate).

K2 turns free text into a structured decision and nothing else. It never
writes prose, never emits a number, and never sees a backend endpoint name --
it is handed semantic capability descriptors and a context of shapes and
presence flags. Structured Outputs constrains the reply when the provider
supports it, but the reply is validated with Pydantic **unconditionally**:
a schema is an optimization, not a guarantee.

K3 is the gate in front of every invocation. It runs four checks that can be
made without executing anything -- availability, schema, permission, budget.
Range and context are deliberately NOT re-implemented here: the existing tool
implementations already bounds-check against the grid metadata and already
refuse an incomplete mission, and a second copy of those rules would drift
from the first. K3 maps their typed errors into the semantic taxonomy instead.

Contract: docs/ai/LunaPath_AI_Chatbot_Scope_v0.3.md sections 12 and 15.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any, Mapping, Optional, Sequence, Union

from pydantic import ValidationError

from .ai_contract import (
    RouterAnswerFromContext,
    RouterFailure,
    RouterInvoke,
    parse_router_output,
    router_json_schema,
)
from .ai_prompt import ROUTER_PROMPT
from .ai_tools import (
    CAPABILITIES,
    CELL_BACKED,
    COMPARE_BACKED,
    PARAM_MODELS,
    AiToolError,
    AnalysisProvider,
    ToolBudget,
)

# Total attempts, not retries after the first. AI-02 section 8.2.
ROUTER_MAX_ATTEMPTS = 2

GateCode = str

# Turkish, deterministic, and never generated by a model: a refusal has to be
# something the operator can act on, so each one names what was refused.
_GATE_MESSAGES: dict[str, str] = {
    "E-SCOPE": (
        "Bu konuda yardımcı olamam. Yalnızca mevcut LunaPath analizine ilişkin "
        "soruları cevaplıyorum."
    ),
    "E-UNSUPPORTED": (
        "Bu hesap sistemde şu an açık değil. Mevcut plan özeti, tek hücre "
        "telemetrisi ve dört profil karşılaştırması yapılabilir."
    ),
    "E-SCHEMA": (
        "İsteğini anladım ama hangi analizi çalıştıracağımı parametreye "
        "çeviremedim. Sorunu biraz daha somutlaştırır mısın?"
    ),
    "E-RANGE": "Verilen değer sistemin kabul ettiği aralığın dışında.",
    "E-BUDGET": (
        "Profil karşılaştırması soru başına yalnızca bir kez çalıştırılabilir. "
        "Bu soruyu parçalara bölelim mi?"
    ),
    "E-NODATA": "Bu bilgi mevcut veri setinde yok.",
    "E-CONTEXT": "Bunu cevaplayabilmem için önce bir analiz çalıştırman gerekiyor.",
    "E-GROUNDING": (
        "Yanıtı doğrulayamadım, bu yüzden yalnızca kayıtlı analiz değerlerini "
        "gösteriyorum."
    ),
}

# The tool layer's own codes, mapped rather than duplicated.
_TOOL_ERROR_TO_GATE: dict[str, str] = {
    "UNKNOWN_TOOL": "E-UNSUPPORTED",
    "INVALID_ARGUMENT": "E-RANGE",
    "MISSION_INCOMPLETE": "E-CONTEXT",
    "BUDGET_EXCEEDED": "E-BUDGET",
}

_REFUSAL_TO_GATE: dict[str, str] = {
    "OUT_OF_SCOPE": "E-SCOPE",
    "MUTATING_REQUEST": "E-SCOPE",
    "UNSUPPORTED_CAPABILITY": "E-UNSUPPORTED",
}

# One gate code, two different things worth telling the operator. A mutating
# request is refused as an ACTION but is a legitimate question: the operator can
# be told which control to use. An out-of-scope question cannot. Both still
# report E-SCOPE, so no new wire code appears and nothing pretends the assistant
# performed anything.
_REFUSAL_MESSAGES: dict[str, str] = {
    "MUTATING_REQUEST": (
        "Asistan salt okunur; bu değeri değiştiremem. Değişikliği sol "
        "paneldeki ilgili denetimden kendin yapabilirsin, ardından rotayı "
        "Generate Route ile yeniden üret."
    ),
}


def gate_message(code: str) -> str:
    return _GATE_MESSAGES.get(code, _GATE_MESSAGES["E-SCHEMA"])


def tool_error_code(error: AiToolError) -> str:
    return _TOOL_ERROR_TO_GATE.get(error.code, "E-SCHEMA")


def refusal_code(code: str) -> str:
    return _REFUSAL_TO_GATE.get(code, "E-SCOPE")


def refusal_message(code: str) -> str:
    """The Turkish text for one router refusal. Deterministic, never generated."""
    return _REFUSAL_MESSAGES.get(code) or gate_message(refusal_code(code))


@dataclass(frozen=True)
class GateResult:
    ok: bool
    code: Optional[GateCode] = None
    message_tr: Optional[str] = None


# ── K2 ───────────────────────────────────────────────────────────────────────

def _router_input(
    question: str,
    history: Sequence[Any],
    capabilities: Sequence[Mapping[str, Any]],
    context: Mapping[str, Any],
) -> list[dict[str, Any]]:
    """Everything K2 is allowed to see.

    Capability descriptors and presence flags only. No metric values, because
    a number here is a number the router could echo back.
    """
    briefing = {
        "capabilities": [
            {
                "code": spec["code"],
                "label": spec["label_tr"],
                "available": spec["available"],
                "notes": spec.get("notes"),
            }
            for spec in capabilities
        ],
        "context": dict(context),
    }
    messages: list[dict[str, Any]] = [
        {"role": "user", "content": json.dumps(briefing, ensure_ascii=False, indent=2)}
    ]
    for message in history[-6:]:
        role = getattr(message, "role", None) or message.get("role")
        content = getattr(message, "content", None) or message.get("content")
        if role in ("user", "assistant") and content:
            messages.append({"role": role, "content": content})
    messages.append({"role": "user", "content": question})
    return messages


def route(
    provider: Any,
    *,
    question: str,
    history: Sequence[Any],
    capabilities: Sequence[Mapping[str, Any]],
    context: Mapping[str, Any],
) -> Union[Any, RouterFailure]:
    """Free text in, one structured decision out."""
    messages = _router_input(question, history, capabilities, context)
    last_error: Optional[str] = None

    for _ in range(ROUTER_MAX_ATTEMPTS):
        attempt_messages = messages
        if last_error is not None:
            attempt_messages = messages + [
                {
                    "role": "user",
                    "content": (
                        "Önceki yanıt şemaya uymadı. Yalnızca şemaya uygun JSON "
                        f"döndür. Hata: {last_error}"
                    ),
                }
            ]
        raw = provider.respond_structured(
            system=ROUTER_PROMPT,
            messages=attempt_messages,
            schema_name="router_output",
            json_schema=router_json_schema(),
        )
        try:
            return parse_router_output(json.loads(raw))
        except (TypeError, ValueError, ValidationError) as exc:
            last_error = str(exc)[:400]

    return RouterFailure(detail=last_error)


# ── K3 ───────────────────────────────────────────────────────────────────────

def gate(
    decision: Any,
    *,
    provider: AnalysisProvider,
    budget: ToolBudget,
) -> GateResult:
    """Deterministic admission control, before anything is executed."""
    # answer_from_context resolves to C-SUMMARY, which needs a plan to exist.
    if isinstance(decision, RouterAnswerFromContext):
        if provider.snapshot.currentPlan is None:
            return GateResult(False, "E-CONTEXT", gate_message("E-CONTEXT"))
        return GateResult(True)

    if not isinstance(decision, RouterInvoke):
        return GateResult(True)

    spec = CAPABILITIES.get(decision.capability)
    if spec is None or not spec["available"]:
        return GateResult(False, "E-UNSUPPORTED", gate_message("E-UNSUPPORTED"))

    # Structurally always true -- there is no capability that writes -- but
    # asserted so a future addition cannot slip past unnoticed.
    if spec["writes"]:
        return GateResult(False, "E-SCOPE", gate_message("E-SCOPE"))

    model = PARAM_MODELS.get(decision.capability)
    if model is not None:
        try:
            model.model_validate(decision.params)
        except ValidationError:
            return GateResult(False, "E-SCHEMA", gate_message("E-SCHEMA"))

    if decision.capability == "C-SUMMARY" and provider.snapshot.currentPlan is None:
        return GateResult(False, "E-CONTEXT", gate_message("E-CONTEXT"))

    # Every compare-backed alias shares one physical computation, so it also
    # shares one budget: renaming the question must not buy a second run.
    if decision.capability in COMPARE_BACKED:
        if provider.snapshot.start is None or provider.snapshot.goal is None:
            return GateResult(False, "E-CONTEXT", gate_message("E-CONTEXT"))
        # Read-only predicate: does not spend, so a refusal costs nothing.
        if budget.compare_calls >= 1:
            return GateResult(False, "E-BUDGET", gate_message("E-BUDGET"))

    # Range is left to the implementation, which already owns the grid extent.
    if decision.capability in CELL_BACKED:
        metadata = provider.grids.get("metadata") or {}
        shape = metadata.get("shape") or []
        if len(shape) >= 2:
            row = decision.params.get("row")
            col = decision.params.get("col")
            if isinstance(row, int) and isinstance(col, int):
                if not (0 <= row < int(shape[0]) and 0 <= col < int(shape[1])):
                    return GateResult(False, "E-RANGE", gate_message("E-RANGE"))

    return GateResult(True)
